<a href="https://colab.research.google.com/github/Yeonbada/EB2023-2/blob/main/1106M2_%EC%97%B0%EB%B0%94%EB%8B%A4_202121493.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 결측데이터 처리하기

## 결측데이터 확인

In [ ]:
# 데이터 불러오기
import pandas as pd
filename='/content/sample_data/train.csv'
df=pd.read_csv(filename)
df.head() #상위 5행 출력 #NaN=데이터 프레임 내에 데이터가 없는 결측 데이터 의미함.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 결측데이터('Embarked') 확인하기
df[df['Embarked'].isna()] #'Embarked'컬럼의 결측 데이터 출력

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

In [ ]:
# 결측데이터('Age') 확인하기
#자료가 많으므로 .head() 설정
df[df['Age'].isna()].head() #Age컬럼에는 너무 많은 결측데이터 존재=>head로 제어(5개만 출력)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q

In [ ]:
# 연습 - 결측데이터('Cabin') 확인하기
#자료가 많으므로 .head() 설정 #자료가 너무 많아 너무 많은 행이 출력되어 코랩이 멍~해짐
df[df['Cabin'].isna()].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [ ]:
# 컬럼별 결측데이터 개수 확인
df.isnull().sum() #데이터 프레임 전체의 각 컬럼별 결측데이터 개수

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## 결측데이터 삭제

In [ ]:
#drop 함수 이용
#Cabin 컬럼 전체 삭제

df.drop('Cabin',axis=1,inplace=True)

In [ ]:
#컬럼 이름 확인
df.columns #위의 코딩으로 인해 Cabin컬럼 없어짐

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [ ]:
#삭제된 데이터 프레임 확인

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

## 결측데이터 대체 : 최빈값으로 채우기

In [ ]:
# 최빈값 찾기
# 'Embarked' 컬럼에 가장 빈번한 값은 S이고, S를 인덱싱 0으로 지정.
df['Embarked'].mode() #결측값을 최빈값으로 대체하기 위해 최빈값을 출력
                      #결과에서 0이 인덱스 번호임

0    S
Name: Embarked, dtype: object

In [ ]:
#Embarked 컬럼의 결측데이터를 인덱싱 0 (값S로 대체)

df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True) #결측 데이터가 2개뿐이므로 이 컬럼 자체를 삭제하는 것이 아니라 결측값 2개를 최빈값으로 대체
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [ ]:
#Embarked 컬럼의 결측데이터 확인
df[df['Embarked'].isna()] #Embarked컬럼에서 이제 결측데이터 출력 안됨

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Embarked]
Index: []

In [ ]:
# 결측데이터가 대체된 데이터 프레임의 전체 결측데이터 확인
df.isnull().sum() #결측데이터가 없다고 뜸(대체 되었기 때문)

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
# 결측데이터 대체되기 전 결측데이터 포함 행들 출력 및 확인
df.loc[61, 'Embarked']

'S'

In [ ]:
df.loc[829, 'Embarked']

'S'

In [ ]:
# 최빈값 찾기
# 'Age' 컬럼에 가장 빈번한 값은 S이고, S를 인덱싱 0으로 지정.
df['Age'].mode()

0    S
Name: Age, dtype: object

In [ ]:
#연습 - Age 컬럼의 결측데이터를 인덱싱 0 값S로 대체
#상위 10행을 출력하여, 인덱싱 5의 결측데이터 대체상태 확인 #head(10)으로 출력
df['Age'].fillna(df['Age'].mode()[0],inplace=True)
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
5,6,0,3,"Moran, Mr. James",male,S,0,0,330877,8.4583,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C

In [ ]:
#연습 - Age 컬럼의 결측데이터 확인
df[df['Age'].isna()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Embarked]
Index: []

In [ ]:
# 결측데이터가 대체된 데이터 프레임의 전체 결측데이터 확인
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
# 결측데이터 대체되기 전 결측데이터 포함 행들 출력 및 확인
#5,17,19 인덱싱  #df.loc[인덱싱, 컬럼이름]
df.loc[5, 'Age']

'S'

In [ ]:
df.loc[17, 'Age']

'S'

In [ ]:
df.loc[19, 'Age']

'S'